name: Build Checkmk MKP

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Start Checkmk
        run: |
          docker pull checkmk/check-mk-raw:2.4.0-latest

          docker run -d \
            --name checkmk \
            -p 8080:5000 \
            checkmk/check-mk-raw:2.4.0-latest

      - name: Wait for site
        run: |
          until docker exec checkmk omd sites
          do
            sleep 5
          done

      - name: Install plugin
        run: |

          docker exec checkmk mkdir -p \
            /omd/sites/cmk/local/lib/python3/cmk_addons/plugins/smseagle/{agent_based,checkman}

          docker cp agent_based/. \
            checkmk:/omd/sites/cmk/local/lib/python3/cmk_addons/plugins/smseagle/agent_based/

          docker cp checkman/. \
            checkmk:/omd/sites/cmk/local/lib/python3/cmk_addons/plugins/smseagle/checkman/

          docker cp manifest/smseagle.manifest \
            checkmk:/omd/sites/cmk/tmp/

      - name: Reload Checkmk
        run: |
          docker exec checkmk su - cmk -c "cmk -R"

      - name: Build MKP
        run: |
          docker exec checkmk \
            su - cmk -c \
            "mkp package /omd/sites/cmk/tmp/smseagle.manifest"

      - name: Find package
        run: |
          docker exec checkmk find /omd/sites/cmk -name "*.mkp"

      - name: Copy package
        run: |
          docker cp \
            checkmk:/omd/sites/cmk/var/check_mk/packages_local/smseagle-*.mkp .

      - name: Inspect package
        run: |
          docker exec checkmk \
            su - cmk -c \
            "mkp inspect /omd/sites/cmk/var/check_mk/packages_local/smseagle-*.mkp"

      - uses: actions/upload-artifact@v4
        with:
          name: smseagle-mkp
          path: "*.mkp"

      - uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: "*.mkp"
